### ISSUE TITLE
Texts for landing page

### ISSUE THREAD

**Issue by omarreiss** [dozer-cloud/dozer-cloud.github.io#5]

**Comment by omarreiss** [comment]
@rkoster so I've made quite some progress today on the website. I've manipulated the html a bit to get good screenshots. But HTML/CSS wise I still have a few issues to conquer. Please take a look at the screenshots and tell me what you think about the texts.

![screen shot 2015-05-09 at 02 16 32](https://cloud.githubusercontent.com/assets/1488816/7547243/fef5c25c-f5f1-11e4-9436-c4a0a152ade9.png)
![screen shot 2015-05-09 at 02 17 43](https://cloud.githubusercontent.com/assets/1488816/7547242/feeba63c-f5f1-11e4-9492-eafbbaa3d754.png)
![screen shot 2015-05-09 at 02 18 17](https://cloud.githubusercontent.com/assets/1488816/7547241/fee74010-f5f1-11e4-891d-d25b144c8e29.png)

Mailchimp signup works BTW.

**Comment by omarreiss** [comment]
Oh BTW, I found one material design framework that had even more stars -> https://github.com/FezVrasta/bootstrap-material-design/tree/master/less

It's a Bootstrap 3 theme, so that means we can enjoy the robustness of Bootstrap with a sweet looking material sauce :stuck_out_tongue_winking_eye:

**Comment by rkoster** [comment]
The dropshadow of the popup in the screens above seems to be cut of
